create table thlush_menu_items
(
    id          bigint generated by default as identity not null,
    name        character varying null,
    description character varying null,
    price       double precision null,
    sgst        double precision null default '0'::double precision,
    cgst        double precision null default '0'::double precision,
    currency    character varying null default '''₹''::character varying'::character varying,
    status      character varying null,
    created_at  timestamp with time zone                not null default now(),
    category_id bigint null,
    constraint thlush_menu_items_pkey primary key (id),
    constraint thlush_menu_items_category_id_fkey foreign KEY (category_id) references thlush_categories (id)
);