create table thlush_categories
(
    id          bigint generated by default as identity not null,
    name        character varying                       not null,
    description character varying null,
    status      character varying                       not null default '''disable'''::character varying,
    created_at  timestamp with time zone                not null default now(),
    updated_at  timestamp with time zone                not null default now(),
    constraint thlush_categories_pkey primary key (id)
);